# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage


osx_image: xcode8.3
language: objective-c


script:
- set -o pipefail && xcodebuild test -workspace Example/MMSCropView.xcworkspace -scheme MMSCropView-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - set -o pipefail && xcodebuild build -workspace Example/MMSCropView.xcworkspace -scheme MMSCropView-Example -sdk iphonesimulator9.3ONLY_ACTIVE_ARCH=NO | xcpretty
